### ISSUE TITLE
javascript error with babel

### ISSUE THREAD

**Issue by martinjrobins** [OxfordRSE/Electron-Sight#36]
After merging in #35, got the following error:
```
A JavaScript error occurred in the main process
Uncaught Exception:
ReferenceError: regeneratorRuntime is not defined
    at /home/mrobins/git/Electron-Sight/src/index.js:46:46
    at Object.<anonymous> (/home/mrobins/git/Electron-Sight/src/index.js:102:2)
    at Object.<anonymous> (/home/mrobins/git/Electron-Sight/src/index.js:128:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.require.extensions.(anonymous function) [as .js] (/home/mrobins/git/Electron-Sight/node_modules/electron-compile/lib/require-hook.js:77:14)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at init (/home/mrobins/git/Electron-Sight/node_modules/electron-compile/lib/config-parser.js:294:16)
```

Perhaps related to https://github.com/babel/babel/issues/8829

**Comment by iamleeg** [comment]
Did you `npm install` after the merge?

**Comment by iamleeg** [comment]
I don't think it's related to the linked bug, I'm not using that configuration and also not using async functions.

**Comment by iamleeg** [comment]
OK, I've reproduced the bug, let me check it out.

**Comment by martinjrobins** [comment]
thanks @iamleeg, all works for me now
